# Generated by Django 4.2.30 on 2026-06-16 20:01

from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guid", models.CharField(max_length=512)),
                ("source_url", models.URLField(max_length=2048)),
                ("url_hash", models.CharField(max_length=64, unique=True)),
                ("original_title", models.CharField(max_length=1024)),
                ("original_summary", models.TextField(blank=True, default="")),
                ("full_text", models.TextField(blank=True, default="")),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("fetched", "Fetched"),
                            ("extracted", "Extracted"),
                            ("rewritten", "Rewritten"),
                            ("published", "Published"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="fetched",
                        max_length=20,
                    ),
                ),
                ("error", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
            },
        ),
        migrations.CreateModel(
            name="TargetSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("base_url", models.URLField()),
                ("auth_user", models.CharField(max_length=255)),
                (
                    "auth_app_password",
                    encrypted_model_fields.fields.EncryptedCharField(),
                ),
                (
                    "default_status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("publish", "Publish")],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Target site",
                "verbose_name_plural": "Target sites",
            },
        ),
        migrations.CreateModel(
            name="WordPressCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wp_category_id", models.IntegerField()),
                ("name", models.CharField(max_length=255)),
                ("slug", models.CharField(max_length=255)),
                ("synced_at", models.DateTimeField(auto_now=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="newsroom.targetsite",
                    ),
                ),
            ],
            options={
                "verbose_name": "WordPress category",
                "verbose_name_plural": "WordPress categories",
                "unique_together": {("site", "wp_category_id")},
            },
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[("rss", "RSS")], default="rss", max_length=20
                    ),
                ),
                ("url", models.URLField()),
                ("enabled", models.BooleanField(default=True)),
                ("fetch_interval_minutes", models.IntegerField(default=60)),
                (
                    "post_status",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                (
                    "tone",
                    models.CharField(
                        choices=[
                            ("neutral", "Neutral"),
                            ("analytical", "Analytical"),
                            ("conversational", "Conversational"),
                        ],
                        default="neutral",
                        max_length=20,
                    ),
                ),
                (
                    "target_length",
                    models.CharField(
                        choices=[
                            ("short", "Short"),
                            ("medium", "Medium"),
                            ("long", "Long"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("last_fetched_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "target_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sources",
                        to="newsroom.wordpresscategory",
                    ),
                ),
                (
                    "target_site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="newsroom.targetsite",
                    ),
                ),
            ],
            options={
                "verbose_name": "Source",
                "verbose_name_plural": "Sources",
            },
        ),
        migrations.CreateModel(
            name="RewrittenContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1024)),
                ("body_html", models.TextField()),
                ("excerpt", models.TextField()),
                ("seo_title", models.CharField(max_length=1024)),
                ("seo_description", models.TextField()),
                ("tags", models.JSONField(default=list)),
                ("provider", models.CharField(max_length=50)),
                ("model", models.CharField(max_length=100)),
                ("input_tokens", models.IntegerField(default=0)),
                ("output_tokens", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rewritten",
                        to="newsroom.article",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rewritten content",
                "verbose_name_plural": "Rewritten content",
            },
        ),
        migrations.AddField(
            model_name="article",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to="newsroom.source",
            ),
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wp_post_id", models.IntegerField(blank=True, null=True)),
                ("wp_url", models.URLField(blank=True, default="", max_length=2048)),
                (
                    "status",
                    models.CharField(
                        choices=[("published", "Published"), ("failed", "Failed")],
                        max_length=20,
                    ),
                ),
                ("error", models.TextField(blank=True, default="")),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publications",
                        to="newsroom.article",
                    ),
                ),
                (
                    "target_site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publications",
                        to="newsroom.targetsite",
                    ),
                ),
            ],
            options={
                "verbose_name": "Publication",
                "verbose_name_plural": "Publications",
                "unique_together": {("article", "target_site")},
            },
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["status"], name="newsroom_ar_status_587447_idx"),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["source", "published_at"], name="newsroom_ar_source__44d0d5_idx"
            ),
        ),
    ]
