# Generated by Django 4.2.30 on 2026-06-17 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsroom", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="add_featured_image",
            field=models.BooleanField(
                default=True,
                help_text="Подбирать изображение записи из стокового банка (если провайдер настроен)",
            ),
        ),
    ]
