# Generated by Django 4.2.30 on 2026-06-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsroom", "0002_source_add_featured_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="require_moderation",
            field=models.BooleanField(
                default=False,
                help_text="Перед публикацией статья ждёт ручного одобрения в админке",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="status",
            field=models.CharField(
                choices=[
                    ("fetched", "Fetched"),
                    ("extracted", "Extracted"),
                    ("rewritten", "Rewritten"),
                    ("pending", "Pending review"),
                    ("rejected", "Rejected"),
                    ("published", "Published"),
                    ("failed", "Failed"),
                    ("skipped", "Skipped"),
                ],
                default="fetched",
                max_length=20,
            ),
        ),
    ]
